const database = "bd3_atv2"

const collection = "bd3_atv2_produtos"

use(database)

db[collection].insertMany([
    {"nome": "Arroz Branco", "valor": 19.99, "quantidade": 100, "fabricante": "Grãos do Sul", "categoria": "Alimentos", "descricao": "Arroz branco de alta qualidade."},
    {"nome": "Celular X10", "valor": 999.99, "quantidade": 50, "fabricante": "TechBrand", "categoria": "Eletrônicos", "descricao": "Smartphone com câmera de alta resolução."},
    {"nome": "Camisa Polo", "valor": 49.99, "quantidade": 200, "fabricante": "Moda Class", "categoria": "Vestuário", "descricao": "Camisa polo confortável e estilosa."},
    {"nome": "Cadeira Ergonomica", "valor": 299.99, "quantidade": 75, "fabricante": "Móveis do Futuro", "categoria": "Casa e Jardim", "descricao": "Cadeira ideal para home office."},
    {"nome": "Faca de Cozinha", "valor": 39.99, "quantidade": 150, "fabricante": "Cozinha Prática", "categoria": "Utensílios", "descricao": "Faca de cozinha com lâmina afiada."},
    {"nome": "Bicicleta Aro 29", "valor": 1499.99, "quantidade": 20, "fabricante": "BikeWorld", "categoria": "Esportes", "descricao": "Bicicleta ideal para trilhas."},
    {"nome": "Tênis Running", "valor": 199.99, "quantidade": 60, "fabricante": "SportStyle", "categoria": "Vestuário", "descricao": "Tênis leve e confortável para corridas."},
    {"nome": "Caderno Universitário", "valor": 12.99, "quantidade": 300, "fabricante": "Papelaria Criativa", "categoria": "Escritório", "descricao": "Caderno com folhas pautadas."},
    {"nome": "Sofá 3 Lugares", "valor": 1199.99, "quantidade": 15, "fabricante": "Estilo Moderno", "categoria": "Móveis", "descricao": "Sofá confortável para sua sala."},
    {"nome": "Monitor 24 Polegadas", "valor": 799.99, "quantidade": 40, "fabricante": "VisualTech", "categoria": "Eletrônicos", "descricao": "Monitor com resolução Full HD."},
    {"nome": "Liquidificador", "valor": 249.99, "quantidade": 100, "fabricante": "Cozinha Rápida", "categoria": "Eletrodomésticos", "descricao": "Liquidificador potente para smoothies."},
    {"nome": "Tênis Casual", "valor": 159.99, "quantidade": 80, "fabricante": "FashionFoot", "categoria": "Vestuário", "descricao": "Tênis versátil para o dia a dia."},
    {"nome": "Camiseta Estampada", "valor": 29.99, "quantidade": 200, "fabricante": "Estilo Urbano", "categoria": "Vestuário", "descricao": "Camiseta com estampa moderna."},
    {"nome": "Pasta Executiva", "valor": 89.99, "quantidade": 50, "fabricante": "Acessórios Profissionais", "categoria": "Escritório", "descricao": "Pasta para documentos e laptop."},
    {"nome": "Luminária LED", "valor": 59.99, "quantidade": 150, "fabricante": "Iluminações", "categoria": "Decoração", "descricao": "Luminária econômica e moderna."},
    {"nome": "Cerveja Artesanal", "valor": 8.99, "quantidade": 250, "fabricante": "BrewMaster", "categoria": "Bebidas", "descricao": "Cerveja artesanal com sabor único."},
    {"nome": "Mesa de Jantar", "valor": 899.99, "quantidade": 30, "fabricante": "Móveis Elegantes", "categoria": "Móveis", "descricao": "Mesa de jantar para 6 pessoas."},
    {"nome": "Fone de Ouvido Bluetooth", "valor": 149.99, "quantidade": 100, "fabricante": "SoundWave", "categoria": "Eletrônicos", "descricao": "Fone sem fio com ótima qualidade de som."},
    {"nome": "Cafeteira Elétrica", "valor": 199.99, "quantidade": 75, "fabricante": "Café do Dia", "categoria": "Eletrodomésticos", "descricao": "Cafeteira para preparo rápido de café."},
    {"nome": "Capa de Celular", "valor": 29.99, "quantidade": 500, "fabricante": "Acessórios Tech", "categoria": "Acessórios", "descricao": "Capa resistente e estilosa."},
    {"nome": "Bola de Futebol", "valor": 49.99, "quantidade": 200, "fabricante": "Sporty", "categoria": "Esportes", "descricao": "Bola de futebol de alta durabilidade."},
    {"nome": "Geladeira Inox", "valor": 3499.99, "quantidade": 10, "fabricante": "ElectroHome", "categoria": "Eletrodomésticos", "descricao": "Geladeira moderna com tecnologia inverter."},
    {"nome": "Corta-Vento", "valor": 79.99, "quantidade": 60, "fabricante": "Moda Aventura", "categoria": "Vestuário", "descricao": "Jaqueta corta-vento ideal para trilhas."},
    {"nome": "Relógio Digital", "valor": 89.99, "quantidade": 120, "fabricante": "TimeTech", "categoria": "Acessórios", "descricao": "Relógio com cronômetro e alarme."},
    {"nome": "Espremedor de Frutas", "valor": 39.99, "quantidade": 150, "fabricante": "Cozinha Saudável", "categoria": "Eletrodomésticos", "descricao": "Espremedor prático e fácil de usar."},
    {"nome": "Jogo de Panelas", "valor": 199.99, "quantidade": 80, "fabricante": "Cozinha Moderna", "categoria": "Utensílios", "descricao": "Conjunto de panelas antiaderentes."},
    {"nome": "Par de Meias", "valor": 9.99, "quantidade": 300, "fabricante": "Moda Conforto", "categoria": "Vestuário", "descricao": "Meias confortáveis e macias."},
    {"nome": "Escova de Dentes Elétrica", "valor": 149.99, "quantidade": 100, "fabricante": "Saúde em Dia", "categoria": "Higiene", "descricao": "Escova que remove mais placa."},
    {"nome": "Balde de Gelo", "valor": 39.99, "quantidade": 200, "fabricante": "Acessórios para Festas", "categoria": "Decoração", "descricao": "Balde de gelo estiloso para festas."},
    {"nome": "Cama Queen Size", "valor": 1499.99, "quantidade": 20, "fabricante": "Móveis Confortáveis", "categoria": "Móveis", "descricao": "Cama espaçosa e confortável."},
    {"nome": "Panela de Pressão", "valor": 129.99, "quantidade": 75, "fabricante": "Cozinha Rápida", "categoria": "Utensílios", "descricao": "Panela que cozinha alimentos rapidamente."},
    {"nome": "Torradeira", "valor": 89.99, "quantidade": 50, "fabricante": "Café e Cia", "categoria": "Eletrodomésticos", "descricao": "Torradeira com múltiplas funções."},
    {"nome": "Mouse Gamer", "valor": 149.99, "quantidade": 120, "fabricante": "GamePro", "categoria": "Eletrônicos", "descricao": "Mouse com alta precisão para jogos."},
    {"nome": "Balança Digital", "valor": 59.99, "quantidade": 150, "fabricante": "Saúde em Casa", "categoria": "Saúde", "descricao": "Balança digital precisa e confiável."},
    {"nome": "Cabo HDMI", "valor": 29.99, "quantidade": 500, "fabricante": "TechAccess", "categoria": "Acessórios", "descricao": "Cabo HDMI de alta velocidade."},
    {"nome": "Chaleira Elétrica", "valor": 149.99, "quantidade": 80, "fabricante": "Cozinha Prática", "categoria": "Eletrodomésticos", "descricao": "Chaleira que aquece água rapidamente."},
    {"nome": "Mochila Escolar", "valor": 79.99, "quantidade": 100, "fabricante": "Acessórios Infantis", "categoria": "Escolar", "descricao": "Mochila espaçosa com várias divisórias."},
    {"nome": "Suporte para Celular", "valor": 19.99, "quantidade": 200, "fabricante": "Acessórios Tech", "categoria": "Acessórios", "descricao": "Suporte ajustável para celular."},
    {"nome": "Roupão de Banho", "valor": 129.99, "quantidade": 60, "fabricante": "Conforto em Casa", "categoria": "Vestuário", "descricao": "Roupão macio e aconchegante."},
    {"nome": "Rádio Bluetooth", "valor": 89.99, "quantidade": 75, "fabricante": "SoundTech", "categoria": "Eletrônicos", "descricao": "Rádio portátil com conexão Bluetooth."},
    {"nome": "Vaso de Flores", "valor": 39.99, "quantidade": 150, "fabricante": "Decorações Naturais", "categoria": "Decoração", "descricao": "Vaso elegante para sua casa."},
    {"nome": "Bicicleta Infantil", "valor": 499.99, "quantidade": 30, "fabricante": "Criança Aventura", "categoria": "Brinquedos", "descricao": "Bicicleta segura para crianças."},
    {"nome": "Fritadeira Elétrica", "valor": 299.99, "quantidade": 40, "fabricante": "Cozinha Saudável", "categoria": "Eletrodomésticos", "descricao": "Fritadeira que reduz o uso de óleo."},
    {"nome": "Cadeira de Escritório", "valor": 399.99, "quantidade": 25, "fabricante": "Móveis Confortáveis", "categoria": "Móveis", "descricao": "Cadeira ergonômica para escritório."},
    {"nome": "Kit de Maquiagem", "valor": 89.99, "quantidade": 100, "fabricante": "Beleza Glam", "categoria": "Beleza", "descricao": "Kit completo de maquiagem para o dia a dia."},
    {"nome": "Colchão Casal", "valor": 799.99, "quantidade": 15, "fabricante": "Sonhos Aconchegantes", "categoria": "Móveis", "descricao": "Colchão confortável para um bom descanso."},
    {"nome": "Cerveja Artesanal IPA", "valor": 12.99, "quantidade": 200, "fabricante": "BrewHouse", "categoria": "Bebidas", "descricao": "Cerveja IPA com notas frutadas."},
    {"nome": "Espelho Decorativo", "valor": 59.99, "quantidade": 150, "fabricante": "DecoraCasa", "categoria": "Decoração", "descricao": "Espelho elegante para sua sala."},
    {"nome": "Lancheira Térmica", "valor": 39.99, "quantidade": 250, "fabricante": "Almoço Prático", "categoria": "Acessórios", "descricao": "Lancheira que mantém a temperatura dos alimentos."},
    {"nome": "Caderno de Receitas", "valor": 29.99, "quantidade": 120, "fabricante": "Cozinha Criativa", "categoria": "Escritório", "descricao": "Caderno para anotar suas receitas favoritas."}
])